"""
Charts are created in Datawrapper and we directly export (copied) the settings from Datawrapper.

chart_data = dw.get_chart_metadata("q6gP0")
visualization_chart_3_settings = chart_data[1]['metadata']['visualize']
"""

hex_colour_lst = ['#c71e1d', '#18a1cd', '#09bb9f', '#ff9f1c', '#8338ec', '#2ec4b6', '#ff006e', '#3a86ff', '#38b000', '#ffbe0b',
                   '#fb5607', '#4cc9f0', '#7209b7', '#f72585', '#4361ee', '#b5179e', '#480ca8', '#3f37c9', '#ef233c', '#72efdd',
                   '#ff7b00', '#80ffdb', '#6a994e', '#bc6c25', '#ff477e', '#0077b6', '#00b4d8', '#90e0ef', '#d62828', '#06d6a0',
                   '#118ab2', '#073b4c', '#e85d04', '#9b5de5', '#00bbf9', '#fee440', '#f15bb5']

distance_category_lst = ['Under 2.5km', '2.5km', '5km', '8km', '10km', '15km', 'Half Marathon', '25km', '30km', 'Marathon', '50km+']

strava_activity_type_lst = ['AlpineSki', 'BackcountrySki', 'Canoeing', 'Crossfit', 'EBikeRide', 'Elliptical', 'Golf', 'Handcycle', 'Hike',
                         'IceSkate', 'InlineSkate', 'Kayaking', 'Kitesurf', 'NordicSki', 'Ride', 'RockClimbing', 'RollerSki', 'Rowing',
                         'Run', 'Sail', 'Skateboard', 'Snowboard', 'Snowshoe', 'Soccer', 'StairStepper', 'StandUpPaddling', 'Surfing',
                         'Swim', 'Velomobile', 'VirtualRide', 'VirtualRun', 'Walk', 'WeightTraining', 'Wheelchair', 'Windsurf', 'Workout', 'Yoga']

# probably can trim but lazy to do it

visualization_chart_3_settings = {
			'columns': {
				'1': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'2': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'3': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'4': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'5': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'6': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'7': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled':
						True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'8': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'9': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'10': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'11': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'prepend': '',
					'barColor': 0,
					'barStyle': 'normal',
					'minWidth': 30,
					'sortable': True,
					'alignment': 'auto',
					'flagStyle': '1x1',
					'showAsBar': False,
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
					'borderLeft': 'none',
					'fixedWidth': False,
					'barRangeMax': '',
					'barRangeMin': '',
					'borderRight': 'none',
					'compactMode': False,
					'customColor': False,
					'replaceFlags': False,
					'showOnMobile': True,
					'customColorBy': 0,
					'showOnDesktop': True,
					'customBarColor': False,
					'barNoBackground': False,
					'borderLeftColor': '#333333',
					'customColorText': {},
					'barColorNegative': False,
					'customBarColorBy': 0,
					'alignmentVertical': 'middle',
					'customColorBackground': {},
					'customColorBarBackground': {}
				},
				'12': {
					'style': {
						'bold': False,
						'color': False,
						'italic': False,
						'fontSize': 1,
						'underline': False,
						'background': False
					},
					'width': 0.2,
					'append': '',
					'format': '0,0',
					'heatmap': {
						'enabled': True
					},
					'sparkline': {
						'area': True,
						'type': 'line',
						'color': '#18a1cd',
						'title': 'Distance distribution by  month',
						'format': '0.[0]a',
						'height': 25,
						'stroke': 2,
						'dotLast': True,
						'enabled': True,
						'colorNeg': 0,
						'dotFirst': True,
						'rangeMax': '',
						'rangeMin': '',
						'labelDiff': False
					},
				},
			},
		} 
